### ISSUE TITLE
svn_checkout_failed unable to conntect to a repo url via tortoise

### ISSUE THREAD

**Issue by oldschmetterhand** [oldschmetterhand/projektmanagement_test#1]
ads

**Comment by BehemothTheCat** [comment]
check out with tortoise to github - geht nicht, will nicht!
![unbenannt](https://user-images.githubusercontent.com/44614662/47909353-f6f8f300-de8f-11e8-87e8-5404eb2e6ba2.PNG)

**Comment by oldschmetterhand** [comment]
habs gerade probiert, bei mir funktionierts ganz normal (ich glaube der franz hats bei unserer Besprechung auch mit tortoise gemacht) --- vllt mal antivirus / firewall etc. abdrehen?

**Comment by BehemothTheCat** [comment]
bei mir ja auch, aber dann kommt nach dem anklicken von OK die Meldung

**Comment by oldschmetterhand** [comment]
hast du einen antivirus oben auf deinem rechner? (kann mich nur dunkel erinnern) 
wenn ja am besten mal kurz deaktivieren --- versuche auch mal die windows firewall auzszuschalten -- zumindest temporär

**Comment by BehemothTheCat** [comment]
habe ich versucht und sogar Avast deinstalliert, trotzdem aber das Gleiche

**Comment by oldschmetterhand** [comment]
mir fällt jetzt auf die schnelle auch nix ein, was ich dir anbieten kann ist dass du kurz bei mir vorbeikommst und ich schaus mir auf deinem pc an ;-)

**Comment by oldschmetterhand** [comment]
problem wird lokal am pc gehoben ---> issue wird geschlossen

**Comment by oldschmetterhand** [comment]
problem wird lokal am pc gehoben ---> issue wird geschlossen
(wsl. problem mit firewall / antivirus / betriebssystem)
